# Make the application available at http://localhost:8080
# These are default settings, but we add them for clarity.
server:
  port: 8095
  contextPath: /

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8096/auth/oauth/token
      userAuthorizationUri: http://localhost:8096/auth/oauth/authorize
      clientId: myauthserver
      clientSecret: verysecretpassword
    resource:
      userInfoUri: http://localhost:8096/auth/user

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external
zuul:
  routes:
    internalApi:
      path: /**
      url: http://localhost:8095/swagger-ui.html
    externalApi:
      path: /external/**
      url: http://some.external.webservice/

proxy:
  auth:
    routes:
      internalApi: oauth2
      externalApi: none